# Generated by Django 6.0.2 on 2026-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('homework', models.IntegerField()),
                ('test_score', models.IntegerField()),
                ('final_grade', models.IntegerField()),
            ],
        ),
    ]
